import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'bn_BD': {
          "app_title": "তথ্য আপা এ্যাপ",
          "greeting": "হ্যালো!",
          "welcome_login": "স্বাগতম! লগইন করুন",
          "phone_label": "ফোন",
          "password_label": "পাসওয়ার্ড",
          "login_btn": "লগইন করুন",
          "task_a": "বাস্তবায়নে",
          "task_b": "সার্বিক সহায়তায়",
          "task_c": "কারিগরি সহায়তায়",
          "new_order": "নতুন অর্ডার",
          "today_delivery": "আজকের ডেলিভারি",
          "total_order": "মোট অর্ডার",
          "total_order_cost": "মোট অর্ডার মূল্য",
          "incomplete_order": "অসম্পূর্ণ অর্ডার",
          "total_merchant": "বিক্রেতার সংখ্যা",
          "appbar_dashboard": "লালসবুজ",
          "drawer_one": "হোম",
          "drawer_two": "প্রোফাইল",
          "drawer_three": "বিক্রেতা যোগ করুন",
          "drawer_four": "সকল বিক্রেতা",
          "logout": "লগ আউট",
          "additional_info": "অতিরিক্ত তথ্য উপাত্ত",
          "id": "আইডি",
          "email": "ইমেইল",
          "district": "জিলা",
          "upazila": "উপজিলা",
          "zip": "জিপ কোড",
          "appbar_add_merchant": "বিক্রেতা যোগ",
          "image_alert_dialog": "ছবি বাছাই করুন",
          "image_note": "বিক্রেতার ছবি বা ব্যবসার লোগো আপলোড করুন, টাইপ : jpg, jpeg, png",
          "store_name": "দোকানের নাম*",
          "merchant_name": "বিক্রেতার নাম*",
          "phone_no_1": "ফোন নং ১*",
          "phone_no_2": "ফোন নং ২",
          "nid": "এন আই ডি নং",
          "select_district": "জেলা বাছাই করুন*",
          "select": "বাছাই করুন",
          "select_upazila": "উপজেলা বাছাই করুন*",
          "member_of_joita": "আপনি কি জয়িতার সদস্য ?",
          "yes": "হ্যাঁ",
          "take_training": "মহিলা সংস্থা থেকে কোন প্রশিক্ষন নিয়েছেন ?",
          "no": "না",
          "select_training_name": "প্রশিক্ষন বাছাই করুন*",
          "payment_way": "বিক্রেতার পেমেন্ট মাধ্যম",
          "select_payment_method": "পেমেন্ট মাধ্যম বাছাই করুন*",
          "bank_account": "ব্যাংক অ্যাকাউন্ট",
          "mobile_banking": "মোবাইল ব্যাংকিং",
          "account_holder_name": "অ্যাকাউন্ট ধারীর নাম*",
          "name_of_bank": "ব্যাংকের নাম*",
          "account_no": "এ্যকাউন্ট নম্বর*",
          "Select_mobile_banking_name": "মোবাইল ব্যাংকিং-এর নাম*",
          "address": "ঠিকানা*",
          "password": "পাসওয়ার্ড*",
          "confirm_password": "কনফার্ম পাসওয়ার্ড*",
          "validated_payment_method": "পেমেন্ট মাধ্যম বাধ্যতামূলক.",
          "validated_account_holder": "অ্যাকাউন্ট ধারীর নাম বাধ্যতামূলক.",
          "validated_bank_name": "ব্যাংকের নাম বাধ্যতামূলক.",
          "validated_ac_number": "এ্যকাউন্ট নম্বর বাধ্যতামূলক.",
          "validated_training_name": "প্রশিক্ষন-এর নাম বাধ্যতামূলক.",
          "add_btn": "যোগ করুন",
          "switch_to_english": "ইংরেজিতে পারিবর্তন করুন"
        },
    ///End of Bangla
        'en_US': {
          "app_title": "Tottho Apa App",
          "greeting": "Hello!",
          "welcome_login": "Welcome, Login First",
          "phone_label": "Phone",
          "password_label": "Password",
          "login_btn": "Login",
          "task_a": "Implemented by",
          "task_b": "Supported by",
          "task_c": "Technical support",
          "new_order": "New Order",
          "today_delivery": "Today Delivery",
          "total_order": "Total Order",
          "total_order_cost": "Total Order Cost",
          "incomplete_order": "Incomplete Order",
          "total_merchant": "Total Merchant",
          "appbar_dashboard": "Laal Sobuj",
          "drawer_one": "Home",
          "drawer_two": "Profile",
          "drawer_three": "Add Merchant",
          "drawer_four": "All Merchant",
          "logout": "Logout",
          "additional_info": "Additional Information",
          "id": "ID",
          "email": "Email",
          "district": "District",
          "upazila": "Upazila",
          "zip": "Zip code",
          "appbar_add_merchant": "Add Merchant",
          "image_alert_dialog": "Select image from",
          "image_note": "Upload a photo for the business of the merchant. Type should be .png, .jpg, .jpeg",
          "store_name": "Store Name*",
          "merchant_name": "Merchant Name*",
          "phone_no_1": "Phone No 1*",
          "phone_no_2": "Phone No 2",
          "nid": "NID",
          "select_district": "Select district*",
          "select_upazila": "Select upazila*",
          "member_of_joita": "Are you a member of Joyeta?",
          "yes": "Yes",
          "take_training": "Are you taking any training from a women\\'s organization?",
          "no": "No",
          "select_training_name": "Select training name*",
          "payment_way": "Merchant Payment Way",
          "select_payment_method": "Select Payment Method*",
          "bank_account": "Bank Account",
          "mobile_banking": "Mobile Banking",
          "account_holder_name": "Account Holder Name*",
          "name_of_bank": "Name of Bank*",
          "account_no": "Account No*",
          "Select_mobile_banking_name": "Select mobile banking name*",
          "address": "Address*",
          "password": "Password*",
          "confirm_password": "Confirm Password*",
          "validated_payment_method": "One Payment method is required.",
          "validated_account_holder": "Account holder name is required.",
          "validated_bank_name": "Bank name is required.",
          "validated_ac_number": "Account number is required.",
          "validated_training_name": "Training name is required.",
          "add_btn": "Submit",
          "switch_to_english": "Switch to English"
        }
      };
}
